
platform :ios, "8.0"

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'MJRefresh',    '~> 3.1.0'
pod 'MJExtension',  '~> 3.0.10'
pod 'ReactiveCocoa','~>2.5'
pod 'IQKeyboardManager', '~> 4.0.5'
pod 'Masonry', '~> 1.0.1'
pod 'LBXScan', '~> 1.1.1'
target :WKKit do

end
